AWSTemplateFormatVersion: "2010-09-09"
Metadata:
  QSLint:
    Exclusions: [W9002, W9003, W9004, W9006]
Description: "Deploys the spothandler to eks cluster using IMDS"
Parameters:
  EksClusterName:
    Type: String
Mappings:
  Config:
    Prefix: { Value: 'eks-quickstart' }
Resources:
  #https://github.com/aws/aws-node-termination-handler
  SpotHandlerHelmChart:
    Type: "AWSQS::Kubernetes::Helm"
    Metadata: { cfn-lint: { config: { ignore_checks: [ E3012 ] } } }
    Properties:
      ClusterID: !Ref EksClusterName
      Namespace: kube-system
      Repository: https://aws.github.io/eks-charts
      Chart: aws-node-termination-handler
      Version: 0.15.3
      Values:
        enableSpotInterruptionDraining: 'true'
        enableRebalanceMonitoring: 'true'
        enableScheduledEventDraining: 'false'

Outputs:
  SpotHandlerReleaseName:
    Value: !Ref SpotHandlerHelmChart