AWSTemplateFormatVersion: "2010-09-09"
Description: "deploy an example workload into an existing kubernetes cluster"
Metadata:
  cfn-lint: { config: { ignore_checks: [W9002, W9003, W9004, W9006, E9007, E9008] } }
Parameters:
  KubeClusterName:
      Type: String
Resources:
  NvidiaDaemonsetInstall:
    Type: "AWSQS::Kubernetes::Resource"
    Metadata: { cfn-lint: { config: { ignore_checks: [E3002] } } }
    Properties:
      ClusterName: !Ref KubeClusterName
      Namespace: kube-system
      # Kubernetes manifest
      Manifest: !Sub |
        apiVersion: apps/v1
        kind: DaemonSet
        metadata:
          name: node-gpu-exporter
          namespace: kube-system
        spec:
          selector:
            matchLabels:
              app: node-gpu-exporter
          template:
            metadata:
              labels:
                app: node-gpu-exporter
            spec:
              priorityClassName: "system-node-critical"
              tolerations:
                - operator: Exists
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: nvidia-gpu-1-worker
                        operator: Exists
                    - matchExpressions:
                      - key: nvidia-gpu-2-worker
                        operator: Exists
                    - matchExpressions:
                      - key: nvidia-gpu-4-worker
                        operator: Exists
                    - matchExpressions:
                      - key: nvidia-gpu-8-worker
                        operator: Exists
              hostPID: true
              containers:
              - name: node-gpu-exporter
                image: mindprince/nvidia_gpu_prometheus_exporter:0.1
                imagePullPolicy: Always
                env:
                - name: MY_NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                - name: MY_POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: MY_NODE_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
                - name: EXCLUDE_PODS
                  value: $(MY_POD_NAME),nvidia-device-plugin-$(MY_NODE_NAME),nvidia-device-plugin-ctr
                - name: CADVISOR_URL
                  value: http://$(MY_NODE_IP):10255
                ports:
                - containerPort: 9445
                  hostPort: 9445
                resources:
                  requests:
                    memory: 30Mi
                    cpu: 100m
                  limits:
                    memory: 50Mi
                    cpu: 200m
        ---
        apiVersion: v1
        kind: Service
        metadata:
          annotations:
            prometheus.io/scrape: 'true'
          name: node-gpu-exporter
          namespace: kube-system
          labels:
            app: node-gpu-exporter
            k8s-app: node-gpu-exporter
        spec:
          type: ClusterIP
          clusterIP: None
          ports:
          - name: http-metrics
            port: 9445
            protocol: TCP
          selector:
            app: node-gpu-exporter

#https://grafana:com/grafana/dashboards/10703: